on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: adam-wallace/todo-react@master
        name: Hello script
        id: hello
        with:
          who-to-greet: 'Adam'
    # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
