on: [push]

jobs:
  hello_world_job_docker:
    runs-on: ubuntu-latest
    name: A job to say hello using docker
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./github/workflows/dockerAction # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  # hello_world_job_javascript:
  #   runs-on: ubuntu-latest
  #   name: A job to say hello using javascript
  #   steps:
  #   - name: Hello world action step
  #     id: hello
  #     uses: actions/hello-world-javascript-action@v1.1
  #     with:
  #       who-to-greet: 'Adam in Node'
  #   # Use the output from the `hello` step
  #   - name: Get the output time
  #     run: echo "The time was ${{ steps.hello.outputs.time }}"
