on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@adam-wallace-patch-1
      - name: hello script
        id: hello
        uses: /action@adam-walace-patch-1
        with:
          who-to-greet: 'Adam'
    # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
